---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---


## 網站資料爬取
```{r}
library(rvest) 
PTT<-"https://www.ptt.cc/bbs/NBA/index.html"
PTT2<-"https://www.ptt.cc/bbs/NBA/index4627.html"
PTT3<-"https://www.ptt.cc/bbs/NBA/index4626.html"
PTT4<-"https://www.ptt.cc/bbs/NBA/index4625.html"
PTT5<-"https://www.ptt.cc/bbs/NBA/index4624.html"
PTT6<-"https://www.ptt.cc/bbs/NBA/index4623.html"
b <- c(PTT,PTT2,PTT3,PTT4,PTT5,PTT6)
frameALL <- NULL

for(n in b){
PTTContent<-read_html(n)
post_title <- PTTContent %>% html_nodes(".title") %>% html_text()
post_title
post_nrec <- PTTContent %>% html_nodes(".nrec") %>% html_text()
post_nrec
post_author <- PTTContent %>% html_nodes(".author") %>% html_text()
post_author


pppt <- data.frame(Title=c(post_title),
                   pushNum=c(post_nrec),
                   Author=c(post_author)
                   )
pppt
frameALL <- rbind(frameALL,pppt)
}

```

## 爬蟲結果呈現
```{r}
knitr::kable (
    frameALL[1:100,c("Title","pushNum","Author")]) 

```

## 解釋爬蟲結果 
```{r}
dim(frameALL) 
```

共爬出111篇標題與title，pushnum，author共3個欄位

```{r}
table(frameALL$Author)
```
分析作者的出現次數

學會爬蟲之後發現，不知道為什麼，用貼六次網址，沒辦法爬出最新的6頁，想學怎樣可以正確爬出來~~
